import localFont from "next/font/local"
import SessionProvider from "./providers/SessionProvider";
import type { Metadata } from "next";
import "./styles/main.scss"

const netflixSans = localFont({
  src: [
    {
      path: '../../public/fonts/NetflixSans-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/NetflixSans-Regular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../public/fonts/NetflixSans-Medium.otf',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/NetflixSans-Bold.otf',
      weight: '700',
      style: 'normal'
    }
  ],
})
export const metadata: Metadata = {
  title: "Home - Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={netflixSans.className}>
      <body>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
